<?php

declare(strict_types=1);

return [
    'quote' => [
        'title' => 'Quote — :product',
        'heading' => 'Quote — :product',
        'item' => 'Item',
        'value_brl' => 'Amount (R$)',
        'production_cost' => 'Production cost',
        'labor' => 'Labor',
        'profit_margin' => 'Profit margin (:pct%)',
        'proposed_value' => 'Proposed amount',
        'validity' => 'Quote valid for 7 days from :date.',
        'footer' => 'Document generated by Precifique on :datetime.',
        'contact' => 'Contact:',
    ],

    'pricing' => [
        'title' => 'Pricing — :product',
        'heading' => 'Pricing sheet — :product',
        'item' => 'Item',
        'currency' => 'R$',
        'materials' => 'Materials',
        'labor' => 'Labor',
        'variable_costs' => 'Variable costs (product)',
        'additional_costs' => 'Additional costs',
        'fixed_cost_share' => 'Fixed cost allocation',
        'total_cost' => 'Total cost',
        'profit' => 'Profit (:pct%)',
        'suggested_price' => 'Suggested selling price',
        'generated_at' => 'Generated on :datetime — Precifique',
    ],
];
